### ISSUE TITLE
cannot open and use

### ISSUE THREAD

**Issue by PillarGaming** [morihofi/CompressVid#1]
Downloaded it (apk) and installed from releases but cannot open in any way 
dont know what else to say 
cant really find any other android compressor already built with downloadable apk release
idk how to use the gradle to make an apk so yeah rip me bozo

**Comment by PillarGaming** [comment]
Im currently on android 13

**Comment by morihofi** [comment]
Hey, first of all, thanks for taking an interest in my app. 

If you're looking for an app launcher, you won't find it. That's on purpose. You can only use the app if you share content with it, e.g. in the gallery of your phone or another app.

Did that answer your question or do you still need help?

**Comment by PillarGaming** [comment]
I thought it would have some interface, but alas, I guess not. Thank you for clearing up the misunderstanding. Sorry for a very late response
Cheers have a good day.
